[package]
name = "ruidi"
version = "0.1.0"
edition = "2018"

[lib]
name = "midi"
path = "src/midi/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
